# Generated by Django 3.2.6 on 2021-08-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_addtask_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
