# Generated by Django 3.2.6 on 2021-08-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_addtask_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='userid',
        ),
    ]
