# Generated by Django 3.2.6 on 2021-08-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_addtask_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.registration'),
        ),
    ]
