# Generated by Django 3.2.6 on 2021-08-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_addtask_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='users',
        ),
    ]
